//     _____                  ____  __.
//    /  _  \ _____ _______  |    |/ _|____  ___.__.
//   /  /_\  \\__  \\_  __ \ |      < \__  \<   |  |
//  /    |    \/ __ \|  | \/ |    |  \ / __ \\___  |
//  \____|__  (____  /__|    |____|__ (____  / ____|
//          \/     \/                \/    \/\/
//
//  Generated by AarKay on 27/12/18.
//  Copyright © 2018 RahulKatariya. All rights reserved.
//

import Foundation

public struct NetworkModel: Codable {
    public let originCountry: String
    public let id: Int
    public let name: String
    public let logoPath: String?

    public init(originCountry: String, id: Int, name: String, logoPath: String?) {
        self.originCountry = originCountry
        self.id = id
        self.name = name
        self.logoPath = logoPath
    }
}
