//     _____                  ____  __.
//    /  _  \ _____ _______  |    |/ _|____  ___.__.
//   /  /_\  \\__  \\_  __ \ |      < \__  \<   |  |
//  /    |    \/ __ \|  | \/ |    |  \ / __ \\___  |
//  \____|__  (____  /__|    |____|__ (____  / ____|
//          \/     \/                \/    \/\/
//
//  Generated by AarKay on 27/12/18.
//  Copyright © 2018 RahulKatariya. All rights reserved.
//

import Restofire

protocol HTTPBinConfigurable: Configurable {}

extension HTTPBinConfigurable {
    static var hTTPBinConfiguration: Configuration {
        var config = Restofire.Configuration.default
        config.host = "httpbin.org"
        return config
    }

    public var configuration: Configuration {
        return Self.hTTPBinConfiguration
    }
}
