//     _____                  ____  __.
//    /  _  \ _____ _______  |    |/ _|____  ___.__.
//   /  /_\  \\__  \\_  __ \ |      < \__  \<   |  |
//  /    |    \/ __ \|  | \/ |    |  \ / __ \\___  |
//  \____|__  (____  /__|    |____|__ (____  / ____|
//          \/     \/                \/    \/\/
//
//  Generated by AarKay on 27/12/18.
//  Copyright © 2018 RahulKatariya. All rights reserved.
//

import Foundation
import CoreData
import RevelationDomain

@objc(CDMovieDetail)
class CDMovieDetail: NSManagedObject, CDDomainable {
    typealias CDModel = CDMovieDetail
    typealias DomainModel = MovieDetail

    @NSManaged var imdbId: String
    @NSManaged var movie: CDMovie?

    static func asDomain(item: CDMovieDetail) -> MovieDetail {
        /// <aarkay asDomain>
        let model = MovieDetail(imdbId: item.imdbId)
        return model
        /// </aarkay>
    }
}
